spring:
  datasource:
    url: jdbc:h2:mem:testdb
    generate-unique-name: false
  jpa:
    hibernate:
      ddl-auto: none
  h2:
    console:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  error:
    include-message: always
