CREATE TABLE PLAN (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  CODE INT UNIQUE,
  NAME VARCHAR(30),
  PRICE DOUBLE
);

CREATE TABLE USER (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  EMAIL VARCHAR(30) UNIQUE,
  PASSWORD VARCHAR(30)
);

CREATE TABLE SUBSCRIPTION (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  USER_ID INT UNIQUE,
  FOREIGN KEY (USER_ID) REFERENCES USER(ID),
  PLAN_ID INT,
  FOREIGN KEY (PLAN_ID) REFERENCES PLAN(ID),
  START_DATE DATE,
  END_DATE DATE
)